#Penguin conf

url:

logo: /images/logo.png
categories_with_dates: [News]
main_category: "About"
team_name: "nealith"

content_hide: true

defaults:
    -
        scope:
            path: ""
        values:
            title: "Nealith"
            description: "My personal gh-pages on GitHub"
            tags: ["Romain","Ringenbach","Romain Ringenbach","nealith"]

simple_color:
    enable: true
    main_color: "#b4e3f0"
    secondary_color: "#2a2a2a"
    third_color: "#5d757c"

# Sass conf

sass:
    sass_dir: _sass
    style: compressed

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: ["strikethrough"]

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
